spring:
  datasource:
    url: mysql://localhost:3306/rentcarDB?createDatabaseIfNotExist=true
    username: root
    password: minati
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
